FROM openjdk:17-jdk-slim
COPY target/nrservicetwo-1.0-SNAPSHOT-jar-with-dependencies.jar /app/nrservicetwo-1.0-SNAPSHOT-jar-with-dependencies.jar
ENTRYPOINT ["java", "-jar", "/app/nrservicetwo-1.0-SNAPSHOT-jar-with-dependencies.jar"]
