networks:
  my-network:
    external: true
    driver: bridge
services:
  mysql:
    build:
      context: ../mysql-docker-container
    image: mysql
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: baron69Tronch
      MYSQL_DATABASE: proverbsdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network
  nrservicetwo:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - my-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/proverbsdb
      SPRING_DATASOURCE_USERNAME: remoteuser
      SPRING_DATASOURCE_PASSWORD: baron69Tronch 

volumes:
  mysql-data: