receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "https://otlp.nr-data.net:4317"
    headers:
      api-key: "${OTEL_EXPORTER_OTLP_HEADERS}"

service:
  telemetry:
    logs:
      level: debug  
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp]

